Security/Authentication/Provider/JWTProvider.php

HI,
This PR add the raw JWT into the Symfony Token, as we sometime need to decode it to fetch informations (iat, exp, etc...).
Thanks,
Jérémy

Improve JWTProvider

---

Resources/doc/index.md
composer.json

Add info to use JWTRefreshTokenBundle when needs refresh tokens.
Refered to #91 issue.

Add JWTRefreshTokenBundle info

---

DependencyInjection/Security/Factory/JWTFactory.php
Resources/doc/1-configuration-reference.md

[DI] [Security] [Factory] added config option
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #99 
| License       | MIT
| Doc PR        | lexik/LexikJWTAuthenticationBundle/Resources/doc/1-configuration-reference.md#55

Add authentication_listener option

---

.travis.yml

| Bug fix?      | no
| New feature?  | no
| License       | MIT
- remove xdebug as it's not used
- remove not used `$COMPOSER_FLAGS`

Adjust .travis.yml file

---

composer.json

Upgrade symfony/* version bound

---

Resources/config/services.xml

Remove deprecated usage of class parameters

---

Event/JWTAuthenticatedEvent.php
LexikJWTAuthenticationBundle.php

See https://insight.sensiolabs.com/projects/67573b6f-e182-4394-b26a-649c323784f6/analyses/32

Cleanup unused use statements

---

composer.json

See https://github.com/lexik/LexikJWTAuthenticationBundle/pull/228#issuecomment-242507398
----

Update authors for 2.0

---

Encoder/DefaultEncoder.php
Signature/LoadedJWS.php
Tests/Encoder/DefaultEncoderTest.php
Tests/Signature/LoadedJWSTest.php

| BC breaks?    | no |
| Fixed tickets | #239 |
Closes #239

Add iat check

---

Resources/doc/2-data-customization.md
Resources/doc/5-encoder-service.md

| BC breaks?    | no |
| Deprecations | yes |
| Fixed tickets | helps in #132 |

Use AppBundle in documentation code samples

---

Security/Authentication/Token/JWTUserToken.php

The security token must be authenticated no matter of the user's roles

---

CONTRIBUTING.md
README.md
Resources/doc/2-data-customization.md

After some months passed to maintain and work on the evolution of this bundle, I feel the documentation can be improved so we could prevent lots of support issues for which the answer is most often in the doc.
Here is a proposal, getting feedbacks from developers would be really appreciated.

Improve the structure of the documentation

---

Resources/doc/index.md

Add mention for impersonation in docs

---

Encoder/DefaultEncoder.php
Tests/Functional/CompleteTokenAuthenticationTest.php
Tests/Functional/DefaultTokenAuthenticationTest.php
Tests/Functional/SubscribedTokenAuthenticationTest.php

Fix uncaught exception on invalid but correctly formatted token using lcobucci encoder

---

Resources/doc/index.md

Add quotes to parameters in YML

---

Resources/doc/1-configuration-reference.md

Fixes 'A database less user provider' link

Fix doc link

---

Services/KeyLoader/KeyDumperInterface.php
Services/KeyLoader/OpenSSLKeyLoader.php
Services/KeyLoader/RawKeyLoader.php

Closes #305.
@Spomky A review from you would be really appreciated.
/cc @scaytrase

Ease sharing keys between parties

---

.travis.yml
Tests/Functional/Utils/CallableEventSubscriber.php
composer.json
phpunit.xml.dist

Btw stop testing on unmaintained Symfony versions (3.0 and 3.1)

Use symfony/phpunit-bridge for testing

---

Resources/doc/3-functional-testing.md

Reverts lexik/LexikJWTAuthenticationBundle#314

Revert "Update 3-functional-testing.md"

---

Resources/doc/3-functional-testing.md

Fix key path in functional testing doc

---

.travis.yml
DependencyInjection/LexikJWTAuthenticationExtension.php
Resources/config/services.xml
Services/JWTManager.php
Tests/Functional/DependencyInjection/AutowiringTest.php
Tests/Stubs/Autowired.php

pending https://github.com/symfony/symfony/pull/22223

Fix autowiring for upcoming Symfony 3.3

---

DependencyInjection/LexikJWTAuthenticationExtension.php
Tests/Functional/DependencyInjection/AutowiringTest.php
Tests/Functional/app/config/config_custom_encoder.yml
Tests/Stubs/Autowired.php

Fixes https://github.com/Spomky-Labs/lexik-jose-bridge/issues/23

Fix encoder autowiring for symfony <3.3

---

DependencyInjection/Security/Factory/JWTFactory.php

Dont use DefinitionDecorator on symfony 3.3+

---

.scrutinizer.yml
.travis.yml
DependencyInjection/Security/Factory/JWTUserFactory.php
Security/Guard/JWTTokenAuthenticator.php
composer.json

Fix Symfony 4 compatibility

---

Tests/TokenExtractor/AuthorizationHeaderTokenExtractorTest.php
TokenExtractor/AuthorizationHeaderTokenExtractor.php

See https://tools.ietf.org/html/rfc6749#section-5.1
Fixes #411

Make the token type case insensitive

---

Exception/JWTDecodeFailureException.php
Exception/JWTEncodeFailureException.php
Resources/config/services.xml
Security/User/JWTUser.php
Security/User/JWTUserProvider.php
Services/KeyLoader/AbstractKeyLoader.php
Signature/LoadedJWS.php
Tests/Functional/DependencyInjection/AutowiringTest.php
Tests/Functional/Utils/CallableEventSubscriber.php
Tests/Functional/app/AppKernel.php
Tests/Services/JWSProvider/AbstractJWSProviderTest.php
Tests/Stubs/Autowired.php

Make authentication Success/Failure handlers autowirable

---

Security/Http/Authentication/AuthenticationFailureHandler.php
Tests/Functional/GetTokenTest.php
Tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php

Fixed onAuthenticationFailure handler to put exception message if needed

---

Resources/doc/index.md

Fix note about authorization header under apache

---

Resources/doc/index.md

It seems routing.yml is actually not the right file, the correct is routes.yml

Update instructions to point to the right file

---

composer.json

Add ext-openssl requirement

---

Resources/config/deprecated.xml

Fix related to https://github.com/lexik/LexikJWTAuthenticationBundle/issues/576

Fix argument order in JWTProvider service declaration

---

Resources/doc/index.md

Hey @chalasr 
I have add some information for Symfony 4 User.
Bundle Registring into Readme.md is unclear with Sf4.

Update Readme with Symfony 4 Version of register

---

DependencyInjection/Configuration.php

Typo in new user_id_claim configuration info

---

Services/JWTManager.php

Make JWTManager::$userIdClaim nullable

---

Resources/doc/2-data-customization.md

Just a tiny fix for an anchor link.

Fix link in table of contents for data customization

---

Resources/doc/3-functional-testing.md

Change to use sf4 static client and pass the credentials as json

Change to use sf4 static client

---

Resources/doc/2-data-customization.md

JWTInvalidListener => JWTNotFoundListener
jwt_invalid_listener => jwt_notfound_listener

Correct name and class for JWTNotFoundListener

---

CHANGELOG.md

Noticed in https://github.com/lexik/LexikJWTAuthenticationBundle/pull/249/files

Revert space typo in CHANGELOG

---

Resources/doc/1-configuration-reference.md

Added the full default config of the automatic secure cookie generation to the config reference.

Updated configuration reference

---

.travis.yml
Encoder/LcobucciJWTEncoder.php
Exception/JWTFailureException.php

Useful for e.g. automatic token renewal.

Expose payload in encode/decode exceptions

---

Security/Guard/JWTTokenAuthenticator.php

Process chain user provider more accurate

Make chain user provider more accurate

---

.travis.yml
Services/JWSProvider/LcobucciJWSProvider.php
Tests/Functional/Command/CheckConfigCommandTest.php
Tests/Services/JWSProvider/AbstractJWSProviderTest.php

Fix ability to set extra standard claims in the input payload

---

Services/JWSProvider/LcobucciJWSProvider.php

Fixes https://github.com/lexik/LexikJWTAuthenticationBundle/pull/797/files#r532671416

Fix compatibility with locbucci/jwt 3.2

---

Services/JWSProvider/LcobucciJWSProvider.php
Tests/DependencyInjection/AutowiringTest.php

Fix undefined variable

---

Services/JWSProvider/LcobucciJWSProvider.php

Fix compatibility for lcobucci/jwt v3.x (bis)

---

Services/JWSProvider/LcobucciJWSProvider.php
Tests/Services/JWSProvider/AbstractJWSProviderTest.php

Fix creating tokens when iat is already set in the payload

---

Resources/doc/2-data-customization.md

I was reading the doc and I think there is a little something missing there.

Add missing $payload argument in createFromPayload example

---

Security/User/JWTUserProvider.php

What if we move this statement:
```php
$class = $this->class;
```
AFTER
```php
if (isset($this->cache[...])) {
return $this->cache[...];
}
```
To save a little bit of memory in case the user is already in cache.

Save a little bit of memory in case the user is already in cache

---

UPGRADE-2.12.md

Add upgrade notes for v2.12

---

DependencyInjection/Security/Factory/JWTAuthenticatorFactory.php
Exception/ExpiredTokenException.php
Security/Authentication/Provider/JWTProvider.php
Security/Firewall/JWTListener.php
Security/Guard/JWTTokenAuthenticator.php
Security/Http/EntryPoint/JWTEntryPoint.php
Services/JWTManager.php

Fix remaining deprecations on Symfony 5.3

---

Security/Authenticator/JWTAuthenticator.php

Am I right or just missing something? :)

JWTAuthenticator logic fix

---

DependencyInjection/Compiler/RegisterLegacyGuardAuthenticatorPass.php
DependencyInjection/Security/Factory/JWTUserFactory.php
LexikJWTAuthenticationBundle.php
Resources/config/token_authenticator.xml

Fix unexpected deprecation about Guard
