- Resources/doc/index.md
As per http://symfony.com/doc/current/best_practices/configuration.html infrastructure parameters should go in the parameters.yml file rather than config.yml, this also enables different token lifetimes and key passphrases for development / production environments.
> Move security details to parameters.yml.dist

- DependencyInjection/LexikJWTAuthenticationExtension.php
- Resources/config/services.xml
- Security/Firewall/JWTListener.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
Fix deprecated warnings and errors during tests for symfony 2.6+.
Used same logic as in FOSUserBundle to handle both SecurityContextInterface and TokenStorageInterface.
> fixed deprecated errors for symfony 2.6 plus

- DependencyInjection/LexikJWTAuthenticationExtension.php
* Use statement was preventing the bundle from properly working
PHP Fatal error:  Class 'Lexik\Bundle\JWTAuthenticationBundle\DependencyInjection\Reference' not found in /vagrant/vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/DependencyInjection/LexikJWTAuthenticationExtension.php on line 43
> Fixing a missing use statement for Reference

- Encoder/JWTEncoderInterface.php
- Event/JWTAuthenticatedEvent.php
- Events.php
- Resources/config/services.xml
- Resources/doc/2-data-customization.md
- Security/Authentication/Provider/JWTProvider.php
- Services/JWTManagerInterface.php
- Tests/Security/Authentication/Provider/JWTProviderTest.php
With this, it is now possible to transpose elements from the JWT payload to the security context's authenticated token.
> Added new event when token is authenticated

- Resources/doc/index.md
I made some time to find how to get the token with a simple `curl` command before guessing it on the testing cookbook.
I propose to add it on the main documentation to get future user life easier. :+1:
> Add a curl sample to get the token

- Event/JWTEncodedEvent.php
- Events.php
- Resources/doc/2-data-customization.md
- Services/JWTManager.php
- Tests/Services/JWTManagerTest.php
Sometimes this is useful (or even essential) to get JWT string right after it is created. This PR introduces new type of event - JWTEncodedEvent which is being dispatched right after JWT is created (encoded) and contains JWT string.
> add JWTEncodedEvent so JWT string is available after its creation

- DependencyInjection/Security/Factory/JWTFactory.php
- Resources/config/services.xml
- Resources/doc/1-configuration-reference.md
- Tests/TokenExtractor/CookieTokenExtractorTest.php
- TokenExtractor/CookieTokenExtractor.php
Hi,
We store the token in a cookie (secure and httponly) in onAuthenticationSuccess like this :
<pre>
public function onAuthenticationSuccess(Request $request, TokenInterface $token)
{
$response = parent::onAuthenticationSuccess($request, $token);
$tokenJWT = json_decode($response->getContent(), true)['token'];
// Ajoute le token avec l'id de l'utilisateur en clé dans les Redis configurés, avec le ttl contenu dans la conf
$this->rms->set($this->redisDB, $token->getUser()->getId(), $tokenJWT, $this->jwtTokenTTL);
// Crée le cookie contenant le token, avec le ttl contenu dans la conf
$response->headers->setCookie(new Cookie('CERBERE', $tokenJWT, (new \DateTime())->add(new \DateInterval('PT' . $this->jwtTokenTTL . 'S')), '/', null, $this->cookieSecure));
return $response;
}
</pre>
Cookie is …
> Add cookie token extractor

- Event/AuthenticationFailureEvent.php
- Event/AuthenticationSuccessEvent.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Security/Http/Authentication/AuthenticationSuccessHandler.php
This PR fixes https://github.com/lexik/LexikJWTAuthenticationBundle/issues/89 .
I've removed the `extends GetResponseEvent` from events : this parent event is bound to the kernel (see the [symfony api doc](http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Event/GetResponseEvent.html)), and does not make sense here. Moreover, the [`GetResponseEvent::setResponse()`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/a0e2f0a0fafdd41ccdba1c368101c242f2463918/Security/Http/Authentication/AuthenticationSuccessHandler.php#L52) method does a `stopPropagation()` and prevents the use of more than one listener.
> Fix authentication event propagation

- DependencyInjection/Security/Factory/JWTFactory.php
PHP Fatal error:  Call to undefined method Symfony\Component\Config\Definition\Builder\ScalarNodeDefinition::scalarNode() in vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/DependencyInjection/Security/Factory/JWTFactory.php on line 145
> Fatal error on console cache:clear

- .travis.yml
- Encoder/JWTEncoder.php
- composer.json
Updated namsho version to allow newer phpseclib.
All of the phpunit tests passed, so I guess it's fine.
This drops the support of PHP 5.3, but I think it's worth it, as more and more libraries use phpseclib 2.0. This resolves conflicts eg with newest google API client library.
> Updated to newest namshi/jose. Dropped support for PHP 5.3

- DependencyInjection/Security/Factory/JWTFactory.php
- Resources/config/services.xml
- Resources/doc/1-configuration-reference.md
- Tests/TokenExtractor/AuthorizationHeaderTokenExtractorTest.php
- TokenExtractor/AuthorizationHeaderTokenExtractor.php
Hi, I need double authentication : HTTP basic for general restriction and JWT at API level.
They both used the same header (Authorization).
This PR allows to use a custom header name for JWT token in order to handle double authentication.
> Add custom authorization header name

- DependencyInjection/Configuration.php
- Services/JWTManager.php
Actually `namshi/jose` does not prevent an empty ttl. Can be useful in some cases instead of setting a really long one.
> Allow empty ttl

- DependencyInjection/Compiler/RequestCompilerPass.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- LexikJWTAuthenticationBundle.php
- Resources/config/services.xml
- Services/JWTManager.php
- composer.json
Hello,
With Symfony 3.0(.1), the Request service has been once for all removed from the service container. This service has been replaced by the request_stack service.
The problem was that the JWTManager is relying on the request service and as this service has been removed...
I don't think it's possible to keep a backward-comptability with SF < 2.4 (ie: SF 2.3, which is a LTS ending in May 2016 ...), so maybe creating a tag could be a workaround?
I remain at your disposal for any further modifications
Regards,
PS : Sorry for the double PR, I made mistakes trying to correct a comment type ...
> Use requestStack instead of request

- Services/JWTManager.php
| Bug fix?      | yes
| New feature?  | no
| Fixes     | #128
| License       | MIT
We had a lot of fatal errors that request is `null` after update to latest version of this bundle, this fixes all (at least from what we notice) of them.
> Always call for master request from request stack

- Security/Firewall/JWTListener.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
In response of issue #124 , in the JWTListener I replaced the Response by a JsonResponse (such as done by the [AuthenticationFailureHandler](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Http/Authentication/AuthenticationFailureHandler.php#L39))  but using the exception's message.
The result is that when the token is found but invalid, the following response is returned :
```json
{
"code": 401,
"message": "Invalid JWT Token"
}
```
Instead of an empty response as it's done currently.
If this makes sense, I can adapt the JWTListenerTest to check the behavior in this specific case (invalid token).
> Add response message in case of invalid token

- Command/CheckOpenSSLCommand.php
- Encoder/JWTEncoder.php
- Resources/config/services.xml
- Services/OpenSSLKeyLoader.php
- Tests/Services/OpenSSLKeyLoaderTest.php
Add a service that loads keys from parameters (key paths and passphrase as arguments of the service).
The service has been injected in the JWTEncoder rather than the 3 parameters, same for the method `checkOpenSSLConfig` that has been moved in the service and now takes no argument.
This also Improve checks for keys and their corresponding exception messages (One for file existing/reading problem, one for openssl loading, this for both public and private keys).
This avoid duplicated code (Command & Encoder) and make the bundle configuration easier to debug (centralised key loading logic).
> Add OpenSSLKeyLoader

- Event/AuthenticationFailureEvent.php
- Event/JWTInvalidEvent.php
- Events.php
- Resources/config/services.xml
- Resources/doc/2-data-customization.md
- Security/Firewall/JWTListener.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
| Bug fix?      | yes  |
| New feature?  | yes  |
| BC breaks?    | no   |
| Fixed tickets | #153 |
This make developers able to subscribe on the  `AUTHENTICATION_FAILURE` / `INVALID_JWT` events.
The first is dispatched when the provider cannot retrieve/authenticate credentials sent to the login route.
The second (new) is dispatched when the listener cannot retrieve/authenticate a token on a secured route.
Tests and documentation have been updated.
> Allow to set a custom response in case of authentication failure or invalid/not found token

- Resources/doc/2-data-customization.md
- Security/Firewall/JWTListener.php
| Bug fix?      | yes  |
| New feature?  | no |
| BC breaks?    | no   |
| Fixed tickets | no |
For now, we can't handle the case of no token found in request, so I revert a part of my previous #157.
The problem is that we can't know if the current request can be done anonymously.
@slashfan If you see any way to know if the current request can be authenticated anonymously or not (retrieve firewall config?), I could be able to add a check and throw the exception only if the request cannot be authenticated anonymously.
> Fix anonymous access by removing the AuthenticationCredentialsNotFoundException 

- .travis.yml
After discussed in #132, we stop supporting Symfony versions lower than 2.8 for the branch 2.0 and `2.x` releases of this bundle, and so stop ensuring compatibility with these Symfony versions on travis-ci .
Open to any suggestion (missing version, specific php version for specific symfony one, ...).
> Remove Symfony versions < 2.8 from travis.yml

- composer.json
> The PSR-4 autoload standard is recommended for modern bundles
From [Symfony best practices for reusable bundles](http://symfony.com/doc/current/cookbook/bundles/best_practices.html#composer-metadata).
> PSR-4 Autoloading

- .travis.yml
As discussed in #167, we stop testing on PHP versions < 5.5.
> Remove PHP 5.4

- composer.json
Like this, anyone can use the `master` branch by requiring `1.x-dev`, and use the `2.0` branch by requiring `2.0.x-dev` (alias automatically added by packagist).
(should be merged in `2.0` too).
> Composer aliases for dev-master & 2.0.

- Resources/doc/2-data-customization.md
- Response/JWTAuthenticationFailureResponse.php
- Response/JWTAuthenticationSuccessResponse.php
- Security/Firewall/JWTListener.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Security/Http/Authentication/AuthenticationSuccessHandler.php
- Security/Http/EntryPoint/JWTEntryPoint.php
- Tests/Functional/config/config.yml
- Tests/Response/JWTAuthenticationFailureResponseTest.php
- Tests/Response/JWTAuthenticationSuccessResponseTest.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
- Tests/Security/Http/EntryPoint/JWTEntryPointTest.php
| BC breaks?    | no  |
| Deprecations | yes |
| Fixed tickets | n/a |
This introduces a generic Response class for successful/failed authentication.
BTW remove duplicated failure Responses with pretty much the same data (3times).
Let me know what do you think.
Steps:
> Add JWTAuthenticationResponse

- .travis.yml
- CHANGELOG.md
- README.md
> Reference compatibility breaks

- Services/OpenSSLKeyLoader.php
Tests are broken on HHVM since the KeyLoader uses `file://`, the problem was hidden before that the OpenSSLKeyLoader exists, because this part was not precisely tested).
So I did the same as in the new key loader added in `2.0`. It now uses `file_get_contents([KEY PATH])` rather than `file://[KEY PATH]` as first argument of `open_ssl_pkey_get`.
> [KeyLoader] Fix tests on HHVM using file_get_contents

- composer.json
When using phpunit `>= 5.4.0`, we this deprecation warning occurs:
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
My first thought was to avoid the deprecations by using `createMock`, but in fact phpunit `5.4` requires PHP `> 5.6`, so it is preferable to require a lower version of phpunit (`^4.1`).
Should be merged on master too.
> Fix phpunit deprecation

- Tests/Functional/config/config.yml
Fix for:
> Not quoting a scalar starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0: 6x
> Quote parameters in functional test configuration

- Event/JWTFailureEventInterface.php
- Event/JWTInvalidEvent.php
- Event/JWTNotFoundEvent.php
- Events.php
- Resources/doc/2-data-customization.md
- Security/Firewall/JWTListener.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
| Branch?       | master
| Bug fix?      |  no
| New feature?  | yes
| Deprecations? | no
| Fixed tickets | #187, https://github.com/lexik/LexikJWTAuthenticationBundle/pull/159#issuecomment-208228006
| Tests pass?   | yes
As discussed in the fixed tickets,, I propose to add a specific `JWT_NOT_FOUND`, making users able to catch this event and set a custom response if they want, or just ignore it.
It can be useful to secure routes that are part of anonymous firewalls, for restrict it to a specific user role for instance, or just have the same behaviour as on `JWT_INVALID`.
Also it introduces an interface implemented by both `JWT_NOT_FOUND` and `JWT_INVALID`, so the same (listener) method can be used to listen on both events. …
> [DX] Add JWTNotFoundEvent

- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- Resources/config/services.xml
- Resources/doc/1-configuration-reference.md
- Resources/doc/5-encoder-service.md
- Tests/Functional/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
This PR modifies the following configuration option:
* the `encryption_algorithm` is renamed into `signature_algorithm`.
Documentation is updated accordingly.
This PR includes minor modifications on the service.xml file.
> Configuration options modified

- DependencyInjection/Configuration.php
- Services/KeyLoader/AbstractKeyLoader.php
- Services/KeyLoader/OpenSSLKeyLoader.php
- Services/KeyLoader/SecLibKeyLoader.php
Since we want to integrate different bridges of JW* libraries, the `*_key_path` options should not be mandatory anymore, because some of their libraries (especially https://github.com/spomky-labs/lexik-jose-bridge) doesn't need this to be configured.
@Spomky, you worked on this in #195 (partially), sorry for that, we will profit of this change to perform some checks (key files existence) via config validation. Let me know what do you think.
> [Configuration] Make *_key_path config options not mandatory

- Event/AuthenticationFailureEvent.php
- Event/AuthenticationSuccessEvent.php
- Event/JWTCreatedEvent.php
- Event/JWTDecodedEvent.php
- Event/JWTFailureEventInterface.php
- Event/JWTNotFoundEvent.php
- Security/Firewall/JWTListener.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Security/Http/Authentication/AuthenticationSuccessHandler.php
- Services/JWTManager.php
- Tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php
- Tests/Services/JWTManagerTest.php
| Branch?       | 2.0
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
This totally remove the ability of injecting request instances in Event classes, plus there is no more need of injecting the `@request_stack` service into the `JWTManager` class.
> Remove deprecated request args

- Resources/config/services.xml
| Branch?       | 2.0
| Bug fix | yes
| Feature | no
| Deprecations? | no
| Tests pass?   | yes
This fixes a big bug introduced in #201 because of an unmerged path (`services.xml`). It caused that a bad value was passed as token ttl, so it is unable to decode any token.
> Fix unmerged path in services.xml after #201

- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- DependencyInjection/Security/Factory/JWTFactory.php
- Resources/config/services.xml
- Services/TokenExtractorMap.php
- Tests/Services/TokenExtractorMapTest.php
- Tests/TokenExtractor/ChainTokenExtractorTest.php
- TokenExtractor/AuthorizationHeaderTokenExtractor.php
- TokenExtractor/ChainTokenExtractor.php
- TokenExtractor/CookieTokenExtractor.php
- TokenExtractor/QueryParameterTokenExtractor.php
- TokenExtractor/TokenExtractorInterface.php
Per title.
This was first included in #184, I split it here for readability.
---------
> Refactor TokenExtractors loading for easy overriding

- CHANGELOG.md
- DependencyInjection/Configuration.php
- DependencyInjection/Security/Factory/JWTFactory.php
This makes use of the useful `canBeDisabled()`/`canBeEnabled()` methods of the Config' `ArrayNodeDefinition`.
From userland pov, the change is not that big but adds some flexibility.
```yaml
authorization_header: ~     # array('enabled' => true, 'name' => 'Authorization', 'prefix' => 'Bearer')
authorization_header: true  # array('enabled' => true, ...)
authorization_header: false # array('enabled' => false, ...)
```
Same for the `query_parameter` and `cookie` ones except that they are default disabled (when they are not set at all).
> Add more flexibility in token extractors configuration

- Resources/config/services.xml
| New feature?  | no |
| BC breaks?    | no  |
| Fixed tickets | ~ |
It can be useful to get the service from a container, plus it would be a too big BC break to privatise it in 2.0.
> Make the default encoder service public

- DependencyInjection/Configuration.php
- Resources/doc/1-configuration-reference.md
- Resources/doc/index.md
- Tests/Encoder/DefaultEncoderTest.php
- Tests/Signature/LoadedJWSTest.php
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no|
| BC breaks? | yes |
| Deprecations | no|
| Fixed tickets | no |
| Tests pass | yes |
86400 seconds (24 hrs) seem to be too high for a token TTL.
This commit reduces this value to 3600 seconds (1 hr).
1 hour should be enough for almost all use cases. If not, a bundle that
provides refresh token implementation will allow to issue another token
when it is expired.
> TTL scaled down

- composer.json
In order to update PhpSecLib to ^2.0 version it has been necessary to update namshi/jose (^7.2). This will drop support to PHP 5.4.
> Update PhpSecLib to ^2.0

- Services/JWSProvider.php
- Services/KeyLoader/KeyLoaderInterface.php
- Services/KeyLoader/OpenSSLKeyLoader.php
- Services/KeyLoader/SecLibKeyLoader.php
- Tests/Functional/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
- Tests/Services/JWSProviderTest.php
Next to #195 where we changed `encryption_algorithm` to `signature_algorithm`, this adapt the (forgotten) existing code, changing `encryptionAlgorithm` to `signatureAlgorithm` everywhere. 
2.0 being not yet released, we must profit to ensure that the introduced features are following good practices, conventions and naming.
@Spomky as you are quite aware of the good practices in term of encoding in general, it would be awesome if you could do a quick review of the terms we use in the corresponding part of our code base, especially on the `2.0` branch after #162.
For instance I thought about `encryption_engine`, is it always correct in the contexts we use it?
Otherwise, what about simply name it `engine`? That would give `encoder.engine` as option name.
Let me know about your suggestions!
> Enhance naming

- CHANGELOG.md
- Encoder/DefaultEncoder.php
- Encoder/JWTEncoderInterface.php
- Event/JWTExpiredEvent.php
- Events.php
- Exception/ExpiredTokenException.php
- Exception/JWTDecodeFailureException.php
- Exception/JWTEncodeFailureException.php
- Exception/JWTFailureException.php
- Resources/doc/2-data-customization.md
- Security/Guard/JWTTokenAuthenticator.php
- Tests/Encoder/DefaultEncoderTest.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
- Tests/Functional/DefaultTokenAuthenticationTest.php
- Tests/Functional/SubscribedTokenAuthenticationTest.php
- Tests/Functional/Utils/CallableEventSubscriber.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- UPGRADE.md
- composer.json
| BC breaks?    | no  |
| Fixed tickets | #223 |
This is IMHO quite useful to have.
I'm not sure the proposed approach of passing the invalid payload to the event and make it accessible from for reusing it is something safe, I would like to have feedbacks. 
Also I'm not really satisfied of the implementation here, looking for suggestions.
Target #184 for complete testing.
> Introduce JWTExpiredEvent

- Encoder/DefaultEncoder.php
Since #162 our encoder uses `Namshi\Jose\JWS` instead of `Namshi\Jose\SimpleJWS`. I just spotted that only `SimpleJWS` set the `iat` claim.
However, I am not sure any check is done on this claim, so maybe it should be done from our encoder, as a bug fix on master (1.x). 
ping @Spomky do you know if I'm wrong?
> Fix iat claim

- DependencyInjection/Compiler/RequestCompilerPass.php
- Event/AuthenticationFailureEvent.php
- Event/AuthenticationSuccessEvent.php
- Event/JWTCreatedEvent.php
- Event/JWTDecodedEvent.php
- Event/JWTNotFoundEvent.php
- LexikJWTAuthenticationBundle.php
- Security/Firewall/JWTListener.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Security/Http/Authentication/AuthenticationSuccessHandler.php
- Services/JWTManager.php
Muting deprecation warnings for internal calls.
Closes #244
> Fix BC break by re-injecting Request instances

- .travis.yml
- CHANGELOG.md
- DependencyInjection/LexikJWTAuthenticationExtension.php
- Encoder/DefaultEncoder.php
- Encoder/LcobucciJWTEncoder.php
- Resources/config/services.xml
- Resources/doc/1-configuration-reference.md
- Resources/doc/5-encoder-service.md
- Services/JWSProvider/DefaultJWSProvider.php
- Services/JWSProvider/JWSProviderInterface.php
- Services/JWSProvider/LcobucciJWSProvider.php
- Services/KeyLoader/RawKeyLoader.php
- Tests/Encoder/DefaultEncoderTest.php
- Tests/Functional/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
- Tests/Functional/TestCase.php
- Tests/Functional/app/AppKernel.php
- Tests/Functional/app/config/config.yml
- Tests/Functional/app/config/config_default.yml
- Tests/Functional/app/config/config_lcobucci.yml
- Tests/Services/JWSProvider/AbstractJWSProviderTest.php
- Tests/Services/JWSProvider/DefaultJWSProviderTest.php
- Tests/Services/JWSProvider/LcobucciJWSProviderTest.php
- Tests/Services/KeyLoader/RawKeyLoaderTest.php
- composer.json
- phpunit.xml.dist
| BC breaks?    | no |
| Fixed tickets | #132 |
This adds an alternative to the default encoder for the same kind of usage level, with a different Api, allowing to validate claims (contrarily to the default one).
> Add a simple built-in encoder based on lcobucci/jwt

- CHANGELOG.md
- DependencyInjection/Configuration.php
- Resources/config/services.xml
- Services/JWSProvider/DefaultJWSProvider.php
- Services/JWSProvider/LcobucciJWSProvider.php
- Services/JWTManager.php
- Tests/Functional/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
- Tests/Services/JWSProvider/AbstractJWSProviderTest.php
- Tests/Services/JWTManagerTest.php
- UPGRADE.md
| BC breaks?    | yes |
| Fixed tickets | n/a |
The encoder should be responsible of setting the `exp` claim and all other standard ones. @Spomky this might have an impact on the `lexik_jose_bridge`, excepted if you set this claim from the encoder anyway.
> Avoid setting exp claim from JWTManager

- UPGRADE.md
Since it is a BC breaking change (see #250).
> Mention that the token_ttl is no more optional in UPGRADE

- Resources/config/services.xml
> Set autowiring types on services with many alternatives like encoder

- Security/Authentication/Token/JWTUserToken.php
In some situations it is useful to get the security provider key from the token. In fact, JWTUserToken is constructed with `$providerKey` but it is never used and there is no getter for it, hence my addition.
It is also consistent with Symfony's `UsernamePasswordToken`, `RememberMeToken` or `PreAuthenticatedToken` which all have such getter.
> Adding `getProviderKey()` to JWTUserToken

- README.md
- Resources/doc/4-cors-requests.md
- Resources/doc/7-manual-token-creation.md
- Resources/doc/index.md
- Security/Http/Authentication/AuthenticationSuccessHandler.php
- Tests/Security/Http/Authentication/AuthenticationSuccessHandlerTest.php
This eases authenticating users programatically using:
```php
return $container
->get('lexik_jwt_authentication.handler.authentication_success')
->handleAuthenticationSuccess($user): Response;
```
or with a given jwt:
```php
$jwtManager = $container->get('lexik_jwt_authentication.jwt_manager');
return $container
->get('lexik_jwt_authentication.handler.authentication_success')
->handleAuthenticationSuccess($user, $jwtManaer->create($user));
```
Fixes #273 and https://github.com/lexik/LexikJWTAuthenticationBundle/issues/273#issuecomment-264449624.
> Ease creating tokens programatically

- DependencyInjection/Configuration.php
Fixes #284 by removing key path validation from our configuration since it's too early for stream wrappers. Paths are still checked at runtime on credentials+jwt login.
/cc @Spomky maybe `SpomkyLabs/JoseBundle` is concerned by this issue too
> Avoid validating key paths before container compilation

- README.md
Delete duplicate "Extending JWTTokenAuthenticator" link into "Further documentation" section
> Delete duplicate link into "Further documentation"

- Security/User/JWTUserProvider.php
- Tests/Security/User/JWTUserProviderTest.php
According to the [UserProviderInterface definition](http://api.symfony.com/3.2/Symfony/Component/Security/Core/User/UserProviderInterface.html#method_refreshUser), the refreshUser method should return an object implementing UserInterface.
This was returning null & causing an error when trying to chain multiple providers together.
> JWTUserProvider refreshUser method must return a User object

- Services/KeyLoader/OpenSSLKeyLoader.php
- Tests/Services/KeyLoader/OpenSSLKeyLoaderTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |yes   |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
> Throw less missleading exception if SSL keys could not be loaded

- TokenExtractor/AuthorizationHeaderTokenExtractor.php
This PR handles cases where `token_extractors.authorization_header.prefix` is null (`~`) or empty (`""`)
```yaml
token_extractors:
authorization_header:
prefix: ~
name: X-Auth-Token
```
> Handle empty or null authorization header prefix, closes #310

- Response/JWTAuthenticationSuccessResponse.php
- Tests/Response/JWTAuthenticationSuccessResponseTest.php
This pull request is regarding Issue #313.
My proposed change would not change to current behavior of the bundle. All it does is respecting any changes being made to the response data during the AUTHENTICATION_SUCCESS event. That is, if an event listener decides to remove the token from the data array, it will no longer be added later.
> feat: Allow for Response Body without JWT Token

- Services/JWSProvider/DefaultJWSProvider.php
- Services/JWSProvider/LcobucciJWSProvider.php
- Signature/LoadedJWS.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
- Tests/Services/JWSProvider/AbstractJWSProviderTest.php
> Allow empty ttl for testing purpose

- Resources/doc/8-jwt-user-provider.md
Hello,
I noticed little errors on documentation when trying to implement JWT my app and just updated for others don't struggle to figure out.
- Provider name was wrong, updated based on[ 1-configuration-reference.md#security-configuration](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#security-configuration). 
- Syntax error fixed on User class example.
> firewall provider name fixed.

- Security/Guard/JWTTokenAuthenticator.php
- Security/User/JWTUserProvider.php
- Security/User/UserProviderWithPayloadSupportsInterface.php
So anybody can plug their own user provider and get access to the payload :)
> Add an extension point on the UserProviderWithPayloadSupportInterface

- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
Replaces #349 
(test suite on symfony 3.4.x needs to be fixed beforehand)
> Don't register lcobucci encoder if lcobucci/jwt is not installed

- LexikJWTAuthenticationBundle.php
- Resources/config/services.xml
Fixes:
> Auto-registration of the command "Lexik\Bundle\JWTAuthenticationBundle\Command\CheckConfigCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead
> Fix sf3.4 command autoregistration deprecation

- Event/JWTDecodedEvent.php
This is usefull to manipulate the payload after decoding. 
Example usage could be if attributes are encrypted while the JWTCreatedEvent is triggered and should be decrypted while decoding.
> Added setPayload to JWTDecodedEvent analogous to JWTCreatedEvent.

- Resources/doc/index.md
New version of openssl generates encrypted private keys which are unusable. I had too look for a way go decrypt it. This gave me a little headache.
> updated installation guide

- Resources/doc/index.md
Change to the documentation as [lafourchette/SwitchUserStatelessBundle](https://github.com/lafourchette/SwitchUserStatelessBundle) no longer appears to be maintained and is no longer necessary since this pull request https://github.com/symfony/symfony/pull/24260
> Update index.md - Remove reference to lafourchette.

- .travis.yml
- Command/CheckConfigCommand.php
- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- README.md
- Resources/config/console.xml
- Resources/config/key_loader.xml
- Resources/doc/index.md
- Services/JWSProvider/LcobucciJWSProvider.php
- Services/KeyLoader/AbstractKeyLoader.php
- Services/KeyLoader/KeyLoaderInterface.php
- Services/KeyLoader/OpenSSLKeyLoader.php
- Services/KeyLoader/RawKeyLoader.php
- Tests/Functional/Command/CheckConfigCommandTest.php
- Tests/Functional/GetTokenTest.php
- Tests/Functional/app/AppKernel.php
- Tests/Functional/app/config/autowiring.yml
- Tests/Functional/app/config/config_custom_encoder.yml
- Tests/Functional/app/config/config_default.yml
- Tests/Functional/app/config/config_lcobucci_hs256.yml
- Tests/Services/KeyLoader/AbstractTestKeyLoader.php
- Tests/Services/KeyLoader/OpenSSLKeyLoaderTest.php
- Tests/Services/KeyLoader/RawKeyLoaderTest.php
- composer.json
> Fix HMAC support

- Command/GenerateTokenCommand.php
- DependencyInjection/Compiler/WireGenerateTokenCommandPass.php
- LexikJWTAuthenticationBundle.php
- Resources/config/console.xml
- Tests/Functional/Command/GenerateTokenCommandTest.php
- Tests/Functional/TestCase.php
- Tests/Functional/app/AppKernel.php
- Tests/Functional/app/config/GenerateTokenCommand/config.yml
For debugging purposes (and more depending on how the tokens are used - i.e. as API keys for example) it's very useful to be able to generate tokens... therefore let's ship a command that does that 👍
> Add a `lexik:jwt:generate-token` command

- Resources/doc/1-configuration-reference.md
- Resources/doc/2-data-customization.md
- Resources/doc/3-functional-testing.md
- Resources/doc/4-cors-requests.md
- Resources/doc/5-encoder-service.md
- Resources/doc/6-extending-jwt-authenticator.md
- Resources/doc/7-manual-token-creation.md
- Resources/doc/8-jwt-user-provider.md
- Resources/doc/index.md
First round of documentation updates.
Includes:
- config file paths according to the Symfony 4 directory structure
- use of `json_login` instead of `form_login`
- use of `HMAC` based signer
and other misc changes
> Update documentation for v2.5 / Symfony 4

- Resources/config/key_loader.xml
Service OpenSSLKeyLoader is deprecated since version 2.5. It triggers
deprecation error as soon as someone tries to include it. Symfony
framework tries to create reflection of it while building the container
and it triggers deprecation as well. Symfony doesn't know anything about this
service being deprecated. Service should be declared as deprecated in
service config, then Symfony won't touch it.
[https://github.com/lexik/LexikJWTAuthenticationBundle/issues/523]
> Make openssl key loader service deprecated

- CHANGELOG.md
- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- Encoder/LcobucciJWTEncoder.php
- Resources/config/deprecated.xml
- Resources/config/jwt_manager.xml
- Security/Authentication/Provider/JWTProvider.php
- Security/Guard/JWTTokenAuthenticator.php
- Services/JWTManager.php
- Services/JWTTokenManagerInterface.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
- Tests/Functional/GetTokenTest.php
- Tests/Functional/app/config/config_user_id_claim.yml
- Tests/Security/Authentication/Provider/JWTProviderTest.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- Tests/Services/JWTManagerTest.php
- composer.json
- phpunit.xml.dist
This PR modifies the claim used to store the user ID in tokens.
Prior this PR, the claim was the same as the `user_entity_field` option (e.g. `username`).
Now the user ID claim can be customized to the standard claim `sub` (subject) as per the [RFC7519 section 4.1.2](https://tools.ietf.org/html/rfc7519#section-4.1.2) or any other value (e.g. `user_id`).
A new configuration option s added: `user_id_claim`. If null, it will have the same value as `user_entity_field`.
This PR also allow a BC with tokens that have already been issued by an application.
> Customizable User ID Claim

- Resources/doc/index.md
Add Symfony 4 sandbox link. 
Il have keep SF2 exemple because on openssl generation token we can see : 
`$ mkdir -p config/jwt # For Symfony3+, no need of the -p option`
> Add: Symfony4 exemple link of sandbox

- Resources/doc/7-manual-token-creation.md
Since SF 4.0, in the controller, it's better to use the interface instead of the service container.
Maybe it can be nice to show the 2 example ?
> Example with Symfony > 4.0

- Event/Event.php
- Security/Guard/JWTTokenAuthenticator.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Security/Http/Authentication/AuthenticationSuccessHandler.php
- Services/JWTManager.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- Tests/Security/Http/Authentication/AuthenticationSuccessHandlerTest.php
- Tests/Services/JWTManagerTest.php
Fix https://github.com/lexik/LexikJWTAuthenticationBundle/pull/637
Having Contracts 1.1 doesn't mean EventDispatcher 4.3 is installed ;)
ping @chalasr
> Fix FC/BC layer for EventDispatcher

- Events.php
This annotation is used for external tools to read information about event class, it's useful for example in PhpStorm with Symfony plugin where it can automatically create the method with correct parameters, it helps speed up development a lot.
> Add event annotations

- Security/Http/Authentication/AuthenticationFailureHandler.php
- Tests/Functional/GetTokenTest.php
- Tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php
> Fixed AuthenticaionFailureHandler to utilize messages from custom exceptions

- Resources/doc/index.md
`genrsa` is superseded by `genpkey`: https://www.openssl.org/docs/manmaster/man1/openssl.html
And `pkey` is the generic "public and private key management". No need to use the algorithm-specific `rsa` command.
> Update the openssl commands to not use "genrsa" and "rsa"

- Security/User/JWTUser.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
use late static binding on `JWTUser` so I as a developer can extend this class (createFromPayload can now return instance of class extending this class)
https://www.php.net/manual/en/language.oop5.late-static-bindings.php
> Use late static binding on JWTUser

- .gitignore
- .travis.yml
- Security/Http/Authentication/AuthenticationFailureHandler.php
- Tests/Functional/GetTokenTest.php
- Tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php
There are 3 issues addressed here. I would have used different PR for each issue but there was problem with travis build env that wouldn't have produced accurate results if not combined.
1. Updated Travis build env as you can see php 5.5 build are failing. Travis has recently [changed it default build env to Xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) and I have explicitly specified it to be "Trusty". 
2. Addresses [the concern](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/650#issuecomment-505123009) of Authentication Exception message to be retrieved by getMessage. I have changed it to getMessageKey method to meet symfony convention, help translation and prevent possible leak of sensitive info to end user. Also addresses #684
3. Adds …
> Authentication Exception Message from its key, Explicit Travis build env, and .idea to gitignore

- .gitignore
- .travis.yml
- Command/GenerateTokenCommand.php
- Security/Firewall/AbstractListener.php
- Security/Firewall/JWTListener.php
- Tests/DependencyInjection/AutowiringTest.php
- Tests/DependencyInjection/LexikJWTAuthenticationExtensionTest.php
- Tests/Encoder/DefaultEncoderTest.php
- Tests/Functional/Command/CheckConfigCommandTest.php
- Tests/Functional/Command/GenerateTokenCommandTest.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
- Tests/Functional/ForwardCompatTestCaseTrait.php
- Tests/Functional/SubscribedTokenAuthenticationTest.php
- Tests/Functional/TestCase.php
- Tests/Functional/app/AppKernel.php
- Tests/Response/JWTAuthenticationSuccessResponseTest.php
- Tests/Security/Authentication/Firewall/JWTListenerTest.php
- Tests/Security/Authentication/Provider/JWTProviderTest.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- Tests/Services/JWSProvider/AbstractJWSProviderTest.php
- Tests/Services/JWSProvider/DefaultJWSProviderTest.php
- Tests/Services/JWSProvider/LcobucciJWSProviderTest.php
- Tests/Services/KeyLoader/AbstractTestKeyLoader.php
- Tests/Services/KeyLoader/OpenSSLKeyLoaderTest.php
- Tests/TokenExtractor/ChainTokenExtractorTest.php
- composer.json
- phpunit.xml.dist
> Symfony 4.4/5.0 compatibility

- Security/Guard/JWTTokenAuthenticator.php
> add ChainUserProvider

- .travis.yml
- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- DependencyInjection/Security/Factory/JWTFactory.php
- README.md
- Resources/config/deprecated_51.xml
- Resources/config/key_loader.xml
- Resources/config/namshi.xml
- Tests/Functional/app/AppKernel.php
- Tests/Functional/app/config/config_router_utf8.yml
- composer.json
In order to fix this deprecation I had to bump the minimum supported php version to 5.6. 
I don't know what the policy is on supporting php versions, but php 5.5 is EOL for a long time now so I guess this is ok to do?
This pr now fixes also other symfony 5.1 deprecations
> Test against symfony 5.1 and fix deprecations

- DependencyInjection/Configuration.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- Resources/config/cookie.xml
- Resources/doc/1-configuration-reference.md
- Security/Http/Cookie/JWTCookieProvider.php
I have added the possibility to choose if the cookie is "secure" or not. This allows when we work in localhost or on a development server that is not in HTTPS that the cookie is created.
I encountered this problem today and I saw that it was not available which is a pity.
See [753](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/753#discussion_r432844990)
Have a nice evening!
> Added the possibility to choose if the cookie is "secure" or not

- DependencyInjection/Security/Factory/JWTFactory.php
Apologies if the message isn't quite right, but figured it was best to try a PR myself rather than expecting someone else to do it :slightly_smiling_face:.
This should fix the remaining indirect deprecation notice due to the changes made to `setDeprecated()` in Symfony 5.1.
Closes #778
> Add deprecation message argument to JWTFactory.php

- Signature/LoadedJWS.php
- Tests/Signature/LoadedJWSTest.php
Bug fix related to https://bugs.php.net/bug.php?id=74274
DateTime format('U') doesn't handle correctly DST. time should be
prefered
> fix day saving transition php

- Security/Authentication/Token/JWTUserToken.php
👋   Hi
> Since symfony/security-http 5.2: Method "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken::getProviderKey()" has been deprecated, rename it to "getFirewallName()" instead.
from https://github.com/symfony/symfony/pull/37942
> Fix Symfony 5.2 getProviderKey deprecation

- Services/JWSProvider/LcobucciJWSProvider.php
- Signature/LoadedJWS.php
- Tests/Functional/GetTokenTest.php
- composer.json
> Fix support for lcobucci/jwt v3.4 and 4.0

- Security/Guard/JWTTokenAuthenticator.php
Set Token on ExpiredTokenException
This can be useful when you want to fetch the token when it is expired.
> Set Token on ExpiredTokenException

- Resources/doc/3-functional-testing.md
`$client = static::createClient();` is already called line 41 and should be called only once per test function.
Closes https://github.com/lexik/LexikJWTAuthenticationBundle/issues/783
> Remove duplicate client from phpunit example

- Services/JWSProvider/LcobucciJWSProvider.php
- Tests/Functional/SubscribedTokenAuthenticationTest.php
> Fix ability to set extra standard claims in the input payload (bis)

- Services/JWTTokenManagerInterface.php
- Services/KeyLoader/KeyLoaderInterface.php
As Psalm return the following errors:
```
ERROR: InvalidDocblock - vendor/lexik/jwt-authentication-bundle/Services/KeyLoader/KeyLoaderInterface.php:25:5 - Badly-formatted @param in docblock for Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\KeyLoaderInterface::loadKey (see https://psalm.dev/008)
/**
* Loads a key from a given type (public or private).
*
* @param resource|string|null
*
* @return resource|string|null
*/
public function loadKey($type);
```
```
ERROR: InvalidDocblock - vendor/lexik/jwt-authentication-bundle/Services/JWTTokenManagerInterface.php:38:5 - Badly-formatted @param in docblock for Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface::setUserIdentityField (see https://psalm.dev/008)
/**
* Sets the field used as identifier to load an user …
```
> Add parameter name in PHPDocs param comment

- Services/JWSProvider/LcobucciJWSProvider.php
- Tests/Services/JWSProvider/AbstractJWSProviderTest.php
- Tests/Services/JWSProvider/LcobucciJWSProviderTest.php
- phpunit.xml.dist
> Use named constructor for lcobucci/jwt Ecdsa signers

- Services/KeyLoader/AbstractKeyLoader.php
- Services/KeyLoader/KeyLoaderInterface.php
This issue:
Making them public instead of protected make possible the use of the very useful Decorator pattern.
Useful when one wants to replace one specific part of a bundle.
This PR relates to #831 but I would like to receive some feedback on this before merging.
> Make AbstractKeyLoader::getSigningKey() and AbstractKeyLoader::getPublicKey public.

- Services/JWTManager.php
Symfony gives annoying deprecation notices when using DebugClassLoader becouse of this extra annotation
> Remove extra \@param annotation from JWTManager::create

- Command/GenerateKeyPairCommand.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- Resources/config/console.xml
- Resources/doc/index.md
- Tests/DependencyInjection/AutowiringTest.php
- Tests/Functional/Command/GenerateKeyPairCommandTest.php
Hello there,
I'd like to remove the most annoying part of the bundle installation: leverage openssl extension to generate the key pair in a one-liner 🙂 
If you like this one, with the `-n` option, we could update the flex recipe (unfamiliar with this, but I assume that's doable) so that public / private keys are generated on the fly during `composer install`.
Thoughts?
Ben
> Feat: add keypair generation command

- Security/Guard/JWTTokenAuthenticator.php
- Security/Http/Authentication/AuthenticationFailureHandler.php
When Authentication fail, the returned message contains: `%var%` that is not replaced. 
Eg with login_throttling:
> "Too many failed login attempts, please try again in %minutes% minute."
> no replace %minutes%
In symfony they use the translator or the `strtr()` function if the translator is not used, in the case of an API login, I'm not sure the Translation is needed, then I directly use the `strtr()` function.
> [Security] On Authentication failure, replace MessageData

- .gitattributes
- .gitignore
Environment specific files were also removed from `.gitattributes`. They should be [globally ignored](https://docs.github.com/es/github/getting-started-with-github/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) in the environment they exist.
> Remove development files from releases

- .github/workflows/ci.yml
- Command/GenerateTokenCommand.php
- DependencyInjection/LexikJWTAuthenticationExtension.php
- DependencyInjection/Security/Factory/JWTFactory.php
- DependencyInjection/Security/Factory/JWTUserFactory.php
- Security/Authentication/Provider/JWTProvider.php
- Security/Firewall/JWTListener.php
- Security/Guard/JWTTokenAuthenticator.php
- Tests/Functional/Bundle/Controller/TestController.php
- Tests/Functional/CompleteTokenAuthenticationTest.php
- Tests/Security/Authentication/Provider/JWTProviderTest.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- Tests/Security/Http/Authentication/AuthenticationSuccessHandlerTest.php
- Tests/Security/User/JWTUserProviderTest.php
- Tests/Services/JWTManagerTest.php
- Tests/Stubs/User.php
This PR takes a stab at handling some of the Security component deprecations in Symfony 5.3 by adding in the relevant compat checks to use the newer APIs when available and falling back to the deprecated APIs when not.  I've also cleared out some compat code that was there to support Symfony <4.4 and is no longer needed.  Lastly, a CI build for Symfony 5.3 is added in and the 5.x-dev build adjusted to target the 5.4 branch.
> Handle misc. Symfony 5.3 deprecations, update CI config

- .gitignore
- DependencyInjection/Security/Factory/JWTAuthenticatorFactory.php
- DependencyInjection/Security/Factory/JWTFactory.php
- LexikJWTAuthenticationBundle.php
- Resources/config/token_authenticator.xml
- Security/Authenticator/JWTAuthenticator.php
- Security/Authenticator/JWTTokenAuthenticator.php
- Security/Guard/JWTTokenAuthenticator.php
- Security/User/JWTUser.php
- Security/User/JWTUserProvider.php
- Security/User/PayloadAwareUserProviderInterface.php
- Services/JWTManager.php
- Services/JWTTokenManagerInterface.php
- Tests/Functional/Command/GenerateTokenCommandTest.php
- Tests/Functional/app/AppKernel.php
- Tests/Functional/app/config/GenerateTokenCommand/config.yml
- Tests/Functional/app/config/base_config.yml
- Tests/Functional/app/config/base_security.yml
- Tests/Functional/app/config/security_in_memory.yml
- Tests/Functional/app/config/security_in_memory_legacy.yml
- Tests/Functional/app/config/security_lexik_jwt_legacy.yml
- Tests/Security/Authenticator/JWTAuthenticatorTest.php
- Tests/Security/Authenticator/JWTTokenAuthenticatorTest.php
- Tests/Security/Guard/JWTTokenAuthenticatorTest.php
- Tests/Stubs/User.php
- composer.json
Working on implementing the new Authenticator system with Passports & Badges in LexikJWT.
Fixes #874
Fixes #866
Fixes #810
> Add new `jwt` authenticator for Symfony 5.3+ Security system

- CHANGELOG.md
`CHANGELOG.md` is showing incorrect year for releases since 2.10.6; giving the appearance of an inactive repository.
> Fix Changelog dates for releases 2.10.6 <=> 2.12.0

- DependencyInjection/Security/Factory/JWTAuthenticatorFactory.php
- Security/Authenticator/JWTAuthenticator.php
- Services/JWTManager.php
- Services/JWTTokenManagerInterface.php
- Tests/Security/Authenticator/JWTAuthenticatorTest.php
- Tests/Services/JWTManagerTest.php
Renaming `decodeFromJsonWebToken()` to `parse()` btw. 
Also I'm thinking to deprecate `decode()` in the next minor as it's redundant with `JWTEncoderInterface::decode` and having a security token as argument is not adapted to the new Symfony authenticator system.
> Fix BC layer around JWTTokenManagerInterface

- Security/User/JWTUser.php
The "@final" annotation for the JWTUser constructor is somewhat inconsistent with the documentation which tells "Note: You can extend the default JWTUser class if that fits your needs." at https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/8-jwt-user-provider.md
> Removing @final for JWTUser constructor

- Security/Http/Authentication/AuthenticationFailureHandler.php
- Tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php
It is not rare for some exceptions to have their status code taken as an HTTP status code. This avoids to have to override/decorate the authentication handler to mutate the returned response
> Forward exception code to the response status code

- DependencyInjection/LexikJWTAuthenticationExtension.php
Since the console command services are loaded only if `Symfony\Component\Console\Application` exists,  and later the extension attempts to modify the service defintion for `lexik_jwt_authentication.generate_keypair_command` (which would not be defined if Symfony Console is not installed), it can lead to breakage if Symfony Console is not installed.
Moved both loading the services configuration file and the definition change to the same conditional.
> Bundle breaks application if Symfony Console not installed
